"""GoodEnough.ai local benchmark foundation."""

from .artifact_store import (
    ArtifactStore,
    FilesystemArtifactStore,
    artifact_ref_for_body,
    parse_verified_artifact,
    sha256_hex,
    storage_ref_for_run,
)
from .fake_provider import FakeProviderBatchPlanner
from .planning import (
    BatchPlanResult,
    BatchPlanSpec,
    BatchPlanner,
    PlanCaseRef,
    PlanSlot,
    RepositoryBatchPlanner,
    build_planned_run,
    iter_plan_slots,
    stable_planned_run_id,
)
from .boundaries import (
    AcceptanceRules,
    ArtifactRef,
    BatchPurpose,
    BatchStatus,
    BenchmarkBatch,
    BenchmarkCase,
    BenchmarkRequest,
    BenchmarkResponse,
    CollectionContext,
    ErrorType,
    HumanOverride,
    IdentityConfidence,
    LocalModelIdentity,
    ModelParameters,
    ModelProfileReference,
    NormalizedAdapterResponse,
    ParseBoundaryRecord,
    PlannedRun,
    ProviderSurface,
    RoutedProviderIdentity,
    RouteSelectionPolicy,
    RawArtifactReference,
    ScoreBoundaryRecord,
    SourceType,
    TaskFamily,
)
from .exceptions import BatchLifecycleError, ConfigLoadError
from .lifecycle import apply_batch_transition
from .profile_loaders import (
    ModelProfileCatalog,
    ModelProfileDocument,
    PriceUnit,
    PricingProvenance,
    PricingSnapshot,
    PricingSnapshotCatalog,
    default_config_root,
    load_model_profiles,
    load_pricing_snapshots,
    synthetic_model_parameters,
)
from .reproduction import (
    BatchReproductionReport,
    compute_reproduction_checksum,
    reproduction_payload,
    verify_batch_reproduction,
)
from .repository import Repository, SQLiteRepository

__all__ = [
    "AcceptanceRules",
    "ArtifactRef",
    "ArtifactStore",
    "BatchPurpose",
    "BatchStatus",
    "BatchReproductionReport",
    "BenchmarkBatch",
    "BenchmarkCase",
    "BenchmarkRequest",
    "BenchmarkResponse",
    "BatchLifecycleError",
    "BatchPlanResult",
    "BatchPlanSpec",
    "BatchPlanner",
    "CollectionContext",
    "ConfigLoadError",
    "ErrorType",
    "FakeProviderBatchPlanner",
    "FilesystemArtifactStore",
    "HumanOverride",
    "IdentityConfidence",
    "LocalModelIdentity",
    "ModelParameters",
    "ModelProfileCatalog",
    "ModelProfileDocument",
    "ModelProfileReference",
    "NormalizedAdapterResponse",
    "ParseBoundaryRecord",
    "PlanCaseRef",
    "PlanSlot",
    "PriceUnit",
    "PricingProvenance",
    "PricingSnapshot",
    "PricingSnapshotCatalog",
    "RepositoryBatchPlanner",
    "PlannedRun",
    "ProviderSurface",
    "RoutedProviderIdentity",
    "RouteSelectionPolicy",
    "RawArtifactReference",
    "Repository",
    "ScoreBoundaryRecord",
    "SQLiteRepository",
    "SourceType",
    "TaskFamily",
    "apply_batch_transition",
    "artifact_ref_for_body",
    "build_planned_run",
    "compute_reproduction_checksum",
    "default_config_root",
    "iter_plan_slots",
    "load_model_profiles",
    "load_pricing_snapshots",
    "stable_planned_run_id",
    "parse_verified_artifact",
    "reproduction_payload",
    "sha256_hex",
    "storage_ref_for_run",
    "synthetic_model_parameters",
    "verify_batch_reproduction",
]

__version__ = "0.1.0"
