"""GoodEnough.ai local benchmark foundation."""

from .artifact_store import (
    ArtifactStore,
    FilesystemArtifactStore,
    artifact_ref_for_body,
    parse_verified_artifact,
    sha256_hex,
    storage_ref_for_run,
)
from .fake_provider import FakeProviderBatchPlanner
from .planning import (
    BatchPlanResult,
    BatchPlanSpec,
    BatchPlanner,
    PlanCaseRef,
    PlanSlot,
    RepositoryBatchPlanner,
    build_planned_run,
    iter_plan_slots,
    stable_planned_run_id,
)
from .boundaries import (
    AcceptanceRules,
    ArtifactRef,
    BatchPurpose,
    BatchStatus,
    BenchmarkBatch,
    BenchmarkCase,
    BenchmarkRequest,
    BenchmarkResponse,
    CollectionContext,
    ErrorType,
    HumanOverride,
    IdentityConfidence,
    ModelParameters,
    ModelProfileReference,
    NormalizedAdapterResponse,
    ParseBoundaryRecord,
    PlannedRun,
    ProviderSurface,
    RawArtifactReference,
    ScoreBoundaryRecord,
    SourceType,
    TaskFamily,
)
from .repository import Repository, SQLiteRepository

__all__ = [
    "AcceptanceRules",
    "ArtifactRef",
    "ArtifactStore",
    "BatchPurpose",
    "BatchStatus",
    "BenchmarkBatch",
    "BenchmarkCase",
    "BenchmarkRequest",
    "BenchmarkResponse",
    "BatchPlanResult",
    "BatchPlanSpec",
    "BatchPlanner",
    "CollectionContext",
    "ErrorType",
    "FakeProviderBatchPlanner",
    "FilesystemArtifactStore",
    "HumanOverride",
    "IdentityConfidence",
    "ModelParameters",
    "ModelProfileReference",
    "NormalizedAdapterResponse",
    "ParseBoundaryRecord",
    "PlanCaseRef",
    "PlanSlot",
    "RepositoryBatchPlanner",
    "PlannedRun",
    "ProviderSurface",
    "RawArtifactReference",
    "Repository",
    "ScoreBoundaryRecord",
    "SQLiteRepository",
    "SourceType",
    "TaskFamily",
    "artifact_ref_for_body",
    "build_planned_run",
    "iter_plan_slots",
    "stable_planned_run_id",
    "parse_verified_artifact",
    "sha256_hex",
    "storage_ref_for_run",
]

__version__ = "0.1.0"
